#!/bin/bash -eux

source .env

#Create config
mkdir -p ./nextcloud/config

cat > ./nextcloud/config/config.php <<EOF
<?php
\$CONFIG = array (
  'trusted_domains' => 
  array (
    0 => '${DOMAIN}',
  ),
  'datadirectory' => '/var/www/html/data',
  'overwrite.cli.url' => 'https://${DOMAIN}',
  'dbtype' => 'mysql',
  'dbname' => 'nextcloud',
  'dbhost' => 'db:3306',
  'dbtableprefix' => 'oc_',
  'dbuser' => 'nextcloud',
  'dbpassword' => '${MYSQL_USER_PW}',
  'theme' => '',
  'maintenance' => false,
  'memcache.local' => '\\OC\\Memcache\\APCu',
);
EOF


#add proxy config for max_upload_size
mkdir -p ./proxy/conf.d

echo "client_max_body_size 10G;" > ./proxy/conf.d/uploadsize.conf

