#!/bin/bash -eux

source .env

#Create config
cat > config.php <<EOF
<?php
\$CONFIG = array (
  'trusted_domains' =>
  array (
    0 => '${DOMAIN}',
  ),
  'datadirectory' => '/var/www/html/data',
  'overwrite.cli.url' => 'https://${DOMAIN}',
  'dbtype' => 'mysql',
  'dbname' => 'nextcloud',
  'dbhost' => 'db:3306',
  'dbtableprefix' => 'oc_',
  'dbuser' => 'nextcloud',
  'dbpassword' => '${MYSQL_USER_PW}',
  'theme' => '',
  'maintenance' => false,
  'memcache.local' => '\\OC\\Memcache\\APCu',
  'memcache.locking' => '\\OC\\Memcache\\Redis',
  'filelocking.enabled' => 'true',
  'redis' => array(
      'host' => 'redis',
      'port' => 6379,
       ),

);
?>
EOF



